name: artrev
description: "A literature review and study app for urogynecology."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.5
  desktop_drop: ^0.5.0
  dio: ^5.3.0
  drift: ^2.11.0
  file_picker: ^9.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.5.0
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod_annotation: ^2.1.1
  sqlite3_flutter_libs: ^0.5.15
  uuid: ^4.5.1
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.7.3
  drift_dev: ^2.11.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
